version: "3"

services:
  php:
    container_name: bookingkit_php
    build: ./php
    restart: always
    ports:
      - 9000:9000
    networks:
      - backend
    volumes:
      - .:/app

networks:
  backend: